# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 16:03
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lideservices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unittype',
            old_name='unit',
            new_name='name',
        ),
        migrations.AddField(
            model_name='unittype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unittype_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unittype',
            name='created_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='unittype',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unittype_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unittype',
            name='modified_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
