# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-19 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lideservices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='medium',
        ),
        migrations.AddField(
            model_name='target',
            name='notes',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
