# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-08 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lideservices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliquot',
            name='aliquot_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aliquot',
            name='frozen',
            field=models.BooleanField(default=True),
        ),
    ]
