# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-18 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lideservices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='filter_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='lideservices.FilterType'),
        ),
    ]
