# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-11 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lideservices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisbatch',
            name='analysis_batch_notes',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='extractionbatch',
            name='re_extraction_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='finalconcentratedsamplevolume',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pcrreplicatebatch',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='reversetranscription',
            name='re_rt_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sample',
            name='arrival_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sample',
            name='elution_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='target',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
