# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-13 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lideservices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inhibition',
            name='analysis_batch',
        ),
        migrations.AddField(
            model_name='inhibition',
            name='extraction_batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inhibitions', to='lideservices.ExtractionBatch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extraction',
            name='inhibition_dna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extractions_dna', to='lideservices.Inhibition'),
        ),
        migrations.AlterField(
            model_name='extraction',
            name='inhibition_rna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extractions_rna', to='lideservices.Inhibition'),
        ),
    ]
