# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-13 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lideservices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcrreplicate',
            name='re_pcr',
            field=models.BooleanField(default=False),
        ),
    ]
