# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-21 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lideservices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extractionbatch',
            old_name='ext_pos_cq_value',
            new_name='ext_pos_dna_cq_value',
        ),
        migrations.RenameField(
            model_name='extractionbatch',
            old_name='ext_pos_invalid',
            new_name='ext_pos_dna_invalid',
        ),
        migrations.RenameField(
            model_name='reversetranscription',
            old_name='rt_pos_cq_value',
            new_name='ext_pos_rna_rt_cq_value',
        ),
        migrations.RenameField(
            model_name='reversetranscription',
            old_name='rt_pos_invalid',
            new_name='ext_pos_rna_rt_invalid',
        ),
        migrations.RemoveField(
            model_name='extractionbatch',
            name='ext_pos_gc_reaction',
        ),
        migrations.RemoveField(
            model_name='reversetranscription',
            name='rt_pos_gc_reaction',
        ),
    ]
