# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-26 13:57
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lideservices', '0002_auto_20180411_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalSampleMeanConcentration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, db_index=True, default=datetime.date.today, null=True)),
                ('modified_date', models.DateField(auto_now=True, null=True)),
                ('sample_mean_concentration', models.DecimalField(blank=True, decimal_places=100, max_digits=120, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finalsamplemeanconcentration_creator', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finalsamplemeanconcentration_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lide_finalsamplemeanconcentration',
            },
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='result',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='result',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='result',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='result',
            name='target',
        ),
        migrations.AlterField(
            model_name='analysisbatch',
            name='analysis_batch_description',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='sample',
            name='study_site_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='sample',
            name='technician_initials',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='fieldunit',
            unique_together=set([('table', 'field')]),
        ),
        migrations.DeleteModel(
            name='Result',
        ),
        migrations.AddField(
            model_name='finalsamplemeanconcentration',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_sample_mean_concentrations', to='lideservices.Sample'),
        ),
        migrations.AddField(
            model_name='finalsamplemeanconcentration',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_sample_mean_concentrations', to='lideservices.Target'),
        ),
        migrations.AlterUniqueTogether(
            name='finalsamplemeanconcentration',
            unique_together=set([('sample', 'target')]),
        ),
    ]
