# Generated by Django 2.2 on 2019-04-08 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lideservices', '0002_auto_20190321_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliquot',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aliquot_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aliquot',
            name='freezer_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aliquot', to='lideservices.FreezerLocation'),
        ),
        migrations.AlterField(
            model_name='aliquot',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aliquot_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aliquot',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aliquots', to='lideservices.Sample'),
        ),
        migrations.AlterField(
            model_name='analysisbatch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analysisbatch_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='analysisbatch',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analysisbatch_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='analysisbatchtemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analysisbatchtemplate_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='analysisbatchtemplate',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analysisbatchtemplate_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='analysisbatchtemplate',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analysisbatchtemplates', to='lideservices.Target'),
        ),
        migrations.AlterField(
            model_name='concentrationtype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='concentrationtype_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='concentrationtype',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='concentrationtype_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='extractionbatch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extractionbatch_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='extractionbatch',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extractionbatch_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='extractionmethod',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extractionmethod_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='extractionmethod',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extractionmethod_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fieldunit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fieldunit_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fieldunit',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fieldunit_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fieldunit',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fieldunits', to='lideservices.Unit'),
        ),
        migrations.AlterField(
            model_name='filtertype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='filtertype_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='filtertype',
            name='matrix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filters', to='lideservices.Matrix'),
        ),
        migrations.AlterField(
            model_name='filtertype',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='filtertype_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='finalconcentratedsamplevolume',
            name='concentration_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='final_concentrated_sample_volumes', to='lideservices.ConcentrationType'),
        ),
        migrations.AlterField(
            model_name='finalconcentratedsamplevolume',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finalconcentratedsamplevolume_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='finalconcentratedsamplevolume',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finalconcentratedsamplevolume_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='finalsamplemeanconcentration',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finalsamplemeanconcentration_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='finalsamplemeanconcentration',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finalsamplemeanconcentration_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='finalsamplemeanconcentration',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='final_sample_mean_concentrations', to='lideservices.Target'),
        ),
        migrations.AlterField(
            model_name='freezer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='freezer_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='freezer',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='freezer_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='freezerlocation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='freezerlocation_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='freezerlocation',
            name='freezer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='freezerlocations', to='lideservices.Freezer'),
        ),
        migrations.AlterField(
            model_name='freezerlocation',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='freezerlocation_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inhibition',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inhibition_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inhibition',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inhibition_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inhibition',
            name='nucleic_acid_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='lideservices.NucleicAcidType'),
        ),
        migrations.AlterField(
            model_name='matrix',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matrix_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='matrix',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matrix_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nucleicacidtype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nucleicacidtype_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nucleicacidtype',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nucleicacidtype_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='otheranalysis',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='otheranalysis_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='otheranalysis',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='otheranalysis_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pcrreplicate',
            name='concentration_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pcrreplicates', to='lideservices.Unit'),
        ),
        migrations.AlterField(
            model_name='pcrreplicate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pcrreplicate_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pcrreplicate',
            name='invalid_override',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pcrreplicates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pcrreplicate',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pcrreplicate_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pcrreplicatebatch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pcrreplicatebatch_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pcrreplicatebatch',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pcrreplicatebatch_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pcrreplicatebatch',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pcrreplicatebatches', to='lideservices.Target'),
        ),
        migrations.AlterField(
            model_name='recordtype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recordtype_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recordtype',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recordtype_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reversetranscription',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversetranscription_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reversetranscription',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversetranscription_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sample',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sample_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sample',
            name='filter_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='lideservices.FilterType'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='matrix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='lideservices.Matrix'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='meter_reading_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='samples_meter_units', to='lideservices.Unit'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sample_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sample',
            name='record_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='lideservices.RecordType'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='lideservices.SampleType'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='lideservices.Study'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='total_volume_sampled_unit_initial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='samples_tvs_units', to='lideservices.Unit'),
        ),
        migrations.AlterField(
            model_name='sampleanalysisbatch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sampleanalysisbatch_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sampleanalysisbatch',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sampleanalysisbatch_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sampleextraction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sampleextraction_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sampleextraction',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sampleextraction_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='samplegroup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='samplegroup_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='samplegroup',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='samplegroup_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='samplesamplegroup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='samplesamplegroup_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='samplesamplegroup',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='samplesamplegroup_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sampletype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sampletype_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sampletype',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sampletype_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='standardcurve',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='standardcurve_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='standardcurve',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='standardcurve_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='study',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='study_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='study',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='study_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='target',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='target_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='target',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='target_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='target',
            name='nucleic_acid_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='lideservices.NucleicAcidType'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='unit',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit_modifier', to=settings.AUTH_USER_MODEL),
        ),
    ]
