# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-02 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lideservices', '0002_auto_20170929_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionbatch',
            name='reextraction_note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
