# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-15 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lideservices', '0002_auto_20171213_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcrreplicate',
            name='replicate_number',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='extraction',
            unique_together=set([('sample', 'extraction_batch')]),
        ),
        migrations.AlterUniqueTogether(
            name='pcrreplicate',
            unique_together=set([('extraction', 'target', 'replicate_number')]),
        ),
    ]
