# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-23 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lideservices', '0002_auto_20180118_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcrreplicate',
            name='pcrreplicate_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcrreplicates', to='lideservices.PCRReplicateBatch'),
        ),
    ]
