# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-02 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lideservices', '0003_extractionbatch_reextraction_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aliquot',
            old_name='aliquot',
            new_name='aliquot_number',
        ),
        migrations.AlterUniqueTogether(
            name='aliquot',
            unique_together=set([('sample', 'aliquot_number')]),
        ),
    ]
