# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-20 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lideservices', '0003_fieldunit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extraction',
            name='inhibition',
        ),
    ]
