# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-19 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lideservices', '0003_auto_20171019_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardcurve',
            name='pos_ctrl_cq',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='standardcurve',
            name='pos_ctrl_cq_range',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
