# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-26 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lideservices', '0003_auto_20180426_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='sampler_name',
            new_name='sampler_name_fk',
        ),
    ]
