# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-10 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lideservices', '0003_auto_20171109_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extraction',
            name='reverse_transcription',
        ),
    ]
