# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-08 16:14
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lideservices', '0003_auto_20171215_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCRReplicateBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, db_index=True, default=datetime.date.today, null=True)),
                ('modified_date', models.DateField(auto_now=True, null=True)),
                ('replicate_number', models.FloatField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('ext_neg_cq_value', models.FloatField(blank=True, null=True)),
                ('ext_neg_gc_reaction', models.FloatField(blank=True, null=True)),
                ('ext_neg_bad_result_flag', models.BooleanField(default=False)),
                ('rt_neg_cq_value', models.FloatField(blank=True, null=True)),
                ('rt_neg_gc_reaction', models.FloatField(blank=True, null=True)),
                ('rt_neg_bad_result_flag', models.BooleanField(default=False)),
                ('pcr_neg_cq_value', models.FloatField(blank=True, null=True)),
                ('pcr_neg_gc_reaction', models.FloatField(blank=True, null=True)),
                ('pcr_neg_bad_result_flag', models.BooleanField(default=False)),
                ('pcr_pos_cq_value', models.FloatField(blank=True, null=True)),
                ('pcr_pos_gc_reaction', models.FloatField(blank=True, null=True)),
                ('pcr_pos_bad_result_flag', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pcrreplicatebatch_creator', to=settings.AUTH_USER_MODEL)),
                ('extraction_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcrreplicatebatches', to='lideservices.Extraction')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pcrreplicatebatch_modifier', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcrreplicatebatches', to='lideservices.Target')),
            ],
            options={
                'db_table': 'lide_pcrreplicatebatch',
            },
        ),
        migrations.RemoveField(
            model_name='controltype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='controltype',
            name='modified_by',
        ),
        migrations.AddField(
            model_name='extractionbatch',
            name='ext_pos_bad_result_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='extractionbatch',
            name='ext_pos_cq_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extractionbatch',
            name='ext_pos_gc_reaction',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pcrreplicate',
            name='pcrreplicate_batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pcrreplicates', to='lideservices.PCRReplicate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reversetranscription',
            name='rt_pos_bad_result_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reversetranscription',
            name='rt_pos_cq_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reversetranscription',
            name='rt_pos_gc_reaction',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pcrreplicate',
            name='concentration_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pcrreplicates', to='lideservices.Unit'),
        ),
        migrations.RemoveField(
            model_name='pcrreplicate',
            name='control_type',
        ),
        migrations.RemoveField(
            model_name='pcrreplicate',
            name='record_type',
        ),
        migrations.RemoveField(
            model_name='pcrreplicate',
            name='replicate_number',
        ),
        migrations.RemoveField(
            model_name='pcrreplicate',
            name='target',
        ),
        migrations.AlterUniqueTogether(
            name='pcrreplicate',
            unique_together=set([('extraction', 'pcrreplicate_batch')]),
        ),
        migrations.AlterUniqueTogether(
            name='reversetranscription',
            unique_together=set([('extraction_batch', 're_rt')]),
        ),
        migrations.DeleteModel(
            name='ControlType',
        ),
        migrations.AlterUniqueTogether(
            name='pcrreplicatebatch',
            unique_together=set([('extraction_batch', 'target', 'replicate_number')]),
        ),
    ]
