# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-23 23:03
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lideservices', '0003_auto_20170717_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aliquot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, db_index=True, default=datetime.date.today, null=True)),
                ('modified_date', models.DateField(auto_now=True, null=True)),
                ('aliquot', models.IntegerField()),
                ('frozen', models.BooleanField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aliquot_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lide_aliquot',
            },
        ),
        migrations.CreateModel(
            name='ConcentrationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, db_index=True, default=datetime.date.today, null=True)),
                ('modified_date', models.DateField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concentrationtype_creator', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concentrationtype_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lide_concentrationtype',
            },
        ),
        migrations.CreateModel(
            name='FinalConcentratedSampleVolume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, db_index=True, default=datetime.date.today, null=True)),
                ('modified_date', models.DateField(auto_now=True, null=True)),
                ('final_concentrated_sample_volume', models.FloatField(blank=True, null=True)),
                ('final_concentrated_sample_volume_notes', models.TextField(blank=True)),
                ('concentration_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lideservices.ConcentrationType')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finalconcentratedsamplevolume_creator', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finalconcentratedsamplevolume_modifier', to=settings.AUTH_USER_MODEL)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lideservices.Sample')),
            ],
            options={
                'db_table': 'lide_finalconcentratedsamplevolume',
            },
        ),
        migrations.CreateModel(
            name='Freezer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, db_index=True, default=datetime.date.today, null=True)),
                ('modified_date', models.DateField(auto_now=True, null=True)),
                ('racks', models.IntegerField()),
                ('boxes', models.IntegerField()),
                ('rows', models.IntegerField()),
                ('spots', models.IntegerField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freezer_creator', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freezer_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lide_freezer',
            },
        ),
        migrations.CreateModel(
            name='FreezerLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, db_index=True, default=datetime.date.today, null=True)),
                ('modified_date', models.DateField(auto_now=True, null=True)),
                ('rack', models.IntegerField()),
                ('box', models.IntegerField()),
                ('row', models.IntegerField()),
                ('spot', models.IntegerField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freezerlocation_creator', to=settings.AUTH_USER_MODEL)),
                ('freezer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freezerlocations', to='lideservices.Freezer')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freezerlocation_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lide_freezer_location',
            },
        ),
        migrations.RemoveField(
            model_name='historicalsamplesamplegroup',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalsamplesamplegroup',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalsamplesamplegroup',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='historicalsamplesamplegroup',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='historicalsamplesamplegroup',
            name='samplegroup',
        ),
        migrations.RemoveField(
            model_name='analysisbatchtemplate',
            name='some_field',
        ),
        migrations.RemoveField(
            model_name='control',
            name='sample',
        ),
        migrations.AddField(
            model_name='analysisbatchtemplate',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='analysisbatchtemplate',
            name='elution_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisbatchtemplate',
            name='extraction_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisbatchtemplate',
            name='name',
            field=models.CharField(default='', max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysisbatchtemplate',
            name='target',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='analysisbatchtemplates', to='lideservices.Target'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='control',
            name='extraction',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='lideservices.Extraction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extraction',
            name='elution_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extraction',
            name='extraction_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samplegroup',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='samplegroup',
            name='name',
            field=models.CharField(default='', max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='extraction',
            unique_together=set([]),
        ),
        migrations.DeleteModel(
            name='HistoricalSampleSampleGroup',
        ),
        migrations.AddField(
            model_name='aliquot',
            name='freezer_location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aliquot', to='lideservices.FreezerLocation'),
        ),
        migrations.AddField(
            model_name='aliquot',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aliquot_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aliquot',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliquots', to='lideservices.Sample'),
        ),
        migrations.AlterUniqueTogether(
            name='aliquot',
            unique_together=set([('sample', 'aliquot')]),
        ),
    ]
