# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-02 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lideservices', '0004_auto_20171002_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraction',
            name='reverse_transcription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to='lideservices.ReverseTranscription'),
        ),
    ]
