# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-26 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lideservices', '0004_auto_20180426_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='sampler_name_fk',
        ),
        migrations.AddField(
            model_name='sample',
            name='sampler_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
