# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-09 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lideservices', '0004_auto_20180108_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcrreplicate',
            name='target',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pcrreplicates', to='lideservices.Target'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='pcrreplicate',
            unique_together=set([('extraction', 'target', 'pcrreplicate_batch')]),
        ),
    ]
