# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-23 23:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lideservices', '0004_auto_20170823_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalconcentratedsamplevolume',
            name='concentration_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_concentrated_sample_volumes', to='lideservices.ConcentrationType'),
        ),
        migrations.AlterField(
            model_name='finalconcentratedsamplevolume',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_concentrated_sample_volumes', to='lideservices.Sample'),
        ),
    ]
