# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-27 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lideservices', '0004_remove_extraction_inhibition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliquot',
            name='aliquot_number',
            field=models.IntegerField(null=True),
        ),
    ]
