# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-26 22:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lideservices', '0004_auto_20180208_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcrreplicate',
            name='bad_result_flag_override',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pcrreplicates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='pcrreplicate',
            name='target',
        ),
        migrations.AlterUniqueTogether(
            name='pcrreplicate',
            unique_together=set([('extraction', 'pcrreplicate_batch')]),
        ),
    ]
