# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-02 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lideservices', '0005_auto_20171002_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reversetranscription',
            name='analysis_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reversetranscriptions', to='lideservices.AnalysisBatch'),
        ),
    ]
