# Generated by Django 2.2 on 2019-05-02 20:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import lideservices.models


class Migration(migrations.Migration):

    dependencies = [
        ('lideservices', '0005_auto_20190424_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionbatch',
            name='inh_pos_cq_value',
            field=lideservices.models.NullableNonnegativeDecimalField2010(blank=True, decimal_places=10, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='extractionbatch',
            name='inh_pos_nucleic_acid_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lideservices.NucleicAcidType'),
        ),
        migrations.AddField(
            model_name='historicalextractionbatch',
            name='inh_pos_cq_value',
            field=lideservices.models.NullableNonnegativeDecimalField2010(blank=True, decimal_places=10, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='historicalextractionbatch',
            name='inh_pos_nucleic_acid_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lideservices.NucleicAcidType'),
        ),
    ]
