# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-01 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lideservices', '0005_auto_20180426_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reversetranscription',
            name='reaction_volume',
            field=models.FloatField(default=50),
        ),
        migrations.AlterField(
            model_name='reversetranscription',
            name='template_volume',
            field=models.FloatField(default=8.6),
        ),
    ]
