# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-27 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lideservices', '0005_auto_20180226_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extractionbatch',
            old_name='reaction_volume',
            new_name='qpcr_reaction_volume',
        ),
        migrations.RenameField(
            model_name='extractionbatch',
            old_name='template_volume',
            new_name='qpcr_template_volume',
        ),
    ]
