# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-19 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lideservices', '0005_auto_20171019_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetmedium',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='targetmedium',
            name='modified_by',
        ),
        migrations.DeleteModel(
            name='TargetMedium',
        ),
    ]
