# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lideservices', '0005_auto_20170823_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalconcentratedsamplevolume',
            name='sample',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_concentrated_sample_volume', to='lideservices.Sample'),
        ),
    ]
