# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-31 05:42
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lideservices', '0006_auto_20171019_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, db_index=True, default=datetime.date.today, null=True)),
                ('modified_date', models.DateField(auto_now=True, null=True)),
                ('sample_mean_concentration', models.FloatField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_creator', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lide_result',
            },
        ),
        migrations.AddField(
            model_name='sample',
            name='peg_neg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='lideservices.Sample'),
        ),
        migrations.AddField(
            model_name='sample',
            name='result',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='lideservices.Result'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='target',
            name='result',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='lideservices.Result'),
            preserve_default=False,
        ),
    ]
