# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-04 21:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lideservices', '0006_auto_20171002_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reversetranscription',
            name='cq_value',
        ),
    ]
