# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-28 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lideservices', '0006_auto_20180227_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractionbatch',
            name='qpcr_reaction_volume',
            field=models.FloatField(blank=True, default=20, null=True),
        ),
        migrations.AlterField(
            model_name='extractionbatch',
            name='qpcr_template_volume',
            field=models.FloatField(blank=True, default=6, null=True),
        ),
    ]
