# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-07 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lideservices', '0007_auto_20180504_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='sample_volume_filtered',
        ),
    ]
