# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-31 06:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lideservices', '0007_auto_20171031_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='sample',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='lideservices.Sample'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='target',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='lideservices.Target'),
            preserve_default=False,
        ),
    ]
