# Generated by Django 2.2 on 2019-10-04 15:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lideservices.models
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lideservices', '0007_auto_20190514_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, db_index=True, default=datetime.date.today, null=True)),
                ('modified_date', models.DateField(auto_now=True, null=True)),
                ('file', models.FileField(upload_to=lideservices.models.ReportFile.reportfile_location)),
                ('report_type', models.IntegerField(choices=[(1, 'Inhibition'), (2, 'ResultsSummary'), (3, 'IndividualSample'), (3, 'QualityControl'), (3, 'ControlsResults')])),
                ('report_status', models.IntegerField(choices=[(1, 'Complete'), (2, 'Pending'), (3, 'Failed')])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reportfile_creator', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reportfile_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lide_reportfile',
            },
        ),
        migrations.CreateModel(
            name='HistoricalReportFile',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, db_index=True, default=datetime.date.today, null=True)),
                ('modified_date', models.DateField(blank=True, editable=False, null=True)),
                ('file', models.TextField(max_length=100)),
                ('report_type', models.IntegerField(choices=[(1, 'Inhibition'), (2, 'ResultsSummary'), (3, 'IndividualSample'), (3, 'QualityControl'), (3, 'ControlsResults')])),
                ('report_status', models.IntegerField(choices=[(1, 'Complete'), (2, 'Pending'), (3, 'Failed')])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical report file',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
