# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-06 11:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lideservices', '0007_remove_reversetranscription_cq_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pcrreplicate',
            name='pcr_date',
        ),
        migrations.RemoveField(
            model_name='pcrreplicate',
            name='template_volume',
        ),
        migrations.AddField(
            model_name='extractionbatch',
            name='pcr_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='extractionbatch',
            name='template_volume',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
