# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-31 06:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lideservices', '0008_auto_20171031_0619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='result',
        ),
        migrations.RemoveField(
            model_name='target',
            name='result',
        ),
    ]
