# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-09 15:56
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lideservices', '0008_remove_sample_sample_volume_filtered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliquot',
            name='aliquot_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='analysisbatchtemplate',
            name='elution_volume',
            field=models.DecimalField(decimal_places=10, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-10'))]),
        ),
        migrations.AlterField(
            model_name='analysisbatchtemplate',
            name='extraction_volume',
            field=models.DecimalField(decimal_places=10, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='extractionbatch',
            name='elution_volume',
            field=models.DecimalField(decimal_places=10, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-10'))]),
        ),
        migrations.AlterField(
            model_name='extractionbatch',
            name='ext_pos_cq_value',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='extractionbatch',
            name='ext_pos_gc_reaction',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='extractionbatch',
            name='extraction_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='extractionbatch',
            name='extraction_volume',
            field=models.DecimalField(decimal_places=10, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='extractionbatch',
            name='qpcr_reaction_volume',
            field=models.DecimalField(decimal_places=10, default=20, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-10'))]),
        ),
        migrations.AlterField(
            model_name='extractionbatch',
            name='qpcr_template_volume',
            field=models.DecimalField(decimal_places=10, default=6, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='extractionbatch',
            name='sample_dilution_factor',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='finalconcentratedsamplevolume',
            name='final_concentrated_sample_volume',
            field=models.DecimalField(decimal_places=100, max_digits=120, validators=[django.core.validators.MinValueValidator(Decimal('1E-100'))]),
        ),
        migrations.AlterField(
            model_name='finalsamplemeanconcentration',
            name='sample_mean_concentration',
            field=models.DecimalField(blank=True, decimal_places=100, max_digits=120, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='freezer',
            name='boxes',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='freezer',
            name='racks',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='freezer',
            name='rows',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='freezer',
            name='spots',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='freezerlocation',
            name='box',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='freezerlocation',
            name='rack',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='freezerlocation',
            name='row',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='freezerlocation',
            name='spot',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='inhibition',
            name='dilution_factor',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pcrreplicate',
            name='cq_value',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pcrreplicate',
            name='gc_reaction',
            field=models.DecimalField(blank=True, decimal_places=100, max_digits=120, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1E-100'))]),
        ),
        migrations.AlterField(
            model_name='pcrreplicate',
            name='replicate_concentration',
            field=models.DecimalField(blank=True, decimal_places=100, max_digits=120, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1E-100'))]),
        ),
        migrations.AlterField(
            model_name='pcrreplicatebatch',
            name='ext_neg_cq_value',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pcrreplicatebatch',
            name='ext_neg_gc_reaction',
            field=models.DecimalField(blank=True, decimal_places=100, max_digits=120, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pcrreplicatebatch',
            name='pcr_neg_cq_value',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pcrreplicatebatch',
            name='pcr_neg_gc_reaction',
            field=models.DecimalField(blank=True, decimal_places=100, max_digits=120, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pcrreplicatebatch',
            name='pcr_pos_cq_value',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pcrreplicatebatch',
            name='pcr_pos_gc_reaction',
            field=models.DecimalField(blank=True, decimal_places=100, max_digits=120, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pcrreplicatebatch',
            name='replicate_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pcrreplicatebatch',
            name='rt_neg_cq_value',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pcrreplicatebatch',
            name='rt_neg_gc_reaction',
            field=models.DecimalField(blank=True, decimal_places=100, max_digits=120, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='reversetranscription',
            name='reaction_volume',
            field=models.DecimalField(decimal_places=10, default=50, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-10'))]),
        ),
        migrations.AlterField(
            model_name='reversetranscription',
            name='rt_pos_cq_value',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='reversetranscription',
            name='rt_pos_gc_reaction',
            field=models.DecimalField(blank=True, decimal_places=100, max_digits=120, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='reversetranscription',
            name='template_volume',
            field=models.DecimalField(decimal_places=10, default=8.6, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sample',
            name='dissolution_volume',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1E-10'))]),
        ),
        migrations.AlterField(
            model_name='sample',
            name='meter_reading_final',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sample',
            name='meter_reading_initial',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sample',
            name='post_dilution_volume',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1E-10'))]),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_volume_initial',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sample',
            name='total_volume_or_mass_sampled',
            field=models.DecimalField(decimal_places=10, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sample',
            name='total_volume_sampled_initial',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='standardcurve',
            name='efficiency',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='standardcurve',
            name='pos_ctrl_cq',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='standardcurve',
            name='pos_ctrl_cq_range',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='standardcurve',
            name='r_value',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='standardcurve',
            name='slope',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
