# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-09 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lideservices', '0008_auto_20180301_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extractionbatch',
            old_name='reextraction',
            new_name='re_extraction',
        ),
        migrations.RenameField(
            model_name='extractionbatch',
            old_name='reextraction_notes',
            new_name='re_extraction_notes',
        ),
    ]
