# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-10 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lideservices', '0008_auto_20171006_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extraction',
            name='dilution_factor',
        ),
        migrations.AddField(
            model_name='extractionbatch',
            name='dilution_factor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
