# Generated by Django 2.2 on 2019-10-04 16:01

from django.db import migrations, models
import lideservices.models


class Migration(migrations.Migration):

    dependencies = [
        ('lideservices', '0008_historicalreportfile_reportfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreportfile',
            name='file',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reportfile',
            name='file',
            field=models.FileField(null=True, upload_to=lideservices.models.ReportFile.reportfile_location),
        ),
    ]
