# Generated by Django 2.2 on 2019-10-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lideservices', '0009_auto_20191004_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreportfile',
            name='fail_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reportfile',
            name='fail_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='historicalreportfile',
            name='report_status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Complete'), (3, 'Failed')]),
        ),
        migrations.AlterField(
            model_name='historicalreportfile',
            name='report_type',
            field=models.IntegerField(choices=[(1, 'Inhibition'), (2, 'ResultsSummary'), (3, 'IndividualSample'), (4, 'QualityControl'), (5, 'ControlsResults')]),
        ),
        migrations.AlterField(
            model_name='reportfile',
            name='report_status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Complete'), (3, 'Failed')]),
        ),
        migrations.AlterField(
            model_name='reportfile',
            name='report_type',
            field=models.IntegerField(choices=[(1, 'Inhibition'), (2, 'ResultsSummary'), (3, 'IndividualSample'), (4, 'QualityControl'), (5, 'ControlsResults')]),
        ),
    ]
