# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-10 13:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lideservices', '0009_auto_20180509_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finalsamplemeanconcentration',
            old_name='sample_mean_concentration',
            new_name='final_sample_mean_concentration',
        ),
        migrations.AlterField(
            model_name='pcrreplicate',
            name='gc_reaction',
            field=models.DecimalField(blank=True, decimal_places=100, max_digits=120, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
