# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-19 13:54
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lideservices', '0010_auto_20180313_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, db_index=True, default=datetime.date.today, null=True)),
                ('modified_date', models.DateField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('code', models.CharField(max_length=128, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matrix_creator', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matrix_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'matrices',
                'db_table': 'lide_matrix',
            },
        ),
        migrations.CreateModel(
            name='SampleExtraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, db_index=True, default=datetime.date.today, null=True)),
                ('modified_date', models.DateField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sampleextraction_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lide_sampleextraction',
            },
        ),
        migrations.AlterUniqueTogether(
            name='extraction',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='extraction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='extraction',
            name='extraction_batch',
        ),
        migrations.RemoveField(
            model_name='extraction',
            name='inhibition_dna',
        ),
        migrations.RemoveField(
            model_name='extraction',
            name='inhibition_rna',
        ),
        migrations.RemoveField(
            model_name='extraction',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='extraction',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='matrixtype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='matrixtype',
            name='modified_by',
        ),
        migrations.AlterModelOptions(
            name='analysisbatch',
            options={'verbose_name_plural': 'analysisbatches'},
        ),
        migrations.AlterModelOptions(
            name='extractionbatch',
            options={'verbose_name_plural': 'extractionbatches'},
        ),
        migrations.AlterModelOptions(
            name='otheranalysis',
            options={'verbose_name_plural': 'otheranalyses'},
        ),
        migrations.AlterModelOptions(
            name='pcrreplicatebatch',
            options={'verbose_name_plural': 'pcrreplicatebatches'},
        ),
        migrations.AlterModelOptions(
            name='sampleanalysisbatch',
            options={'verbose_name_plural': 'sampleanalysisbatches'},
        ),
        migrations.AlterModelOptions(
            name='study',
            options={'verbose_name_plural': 'studies'},
        ),
        migrations.RenameField(
            model_name='finalconcentratedsamplevolume',
            old_name='final_concentrated_sample_volume_notes',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='pcrreplicate',
            old_name='bad_result_flag',
            new_name='invalid',
        ),
        migrations.RenameField(
            model_name='pcrreplicate',
            old_name='bad_result_flag_override',
            new_name='invalid_override',
        ),
        migrations.RemoveField(
            model_name='reversetranscription',
            name='rt_pos_bad_result_flag',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='matrix_type',
        ),
        migrations.AddField(
            model_name='extractionbatch',
            name='ext_pos_invalid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='freezer',
            name='name',
            field=models.CharField(default='freezer', max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pcrreplicatebatch',
            name='ext_neg_invalid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pcrreplicatebatch',
            name='pcr_neg_invalid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pcrreplicatebatch',
            name='pcr_pos_invalid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pcrreplicatebatch',
            name='rt_neg_invalid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reversetranscription',
            name='rt_pos_invalid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='symbol',
            field=models.CharField(default='L', max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aliquot',
            name='aliquot_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analysisbatch',
            name='analysis_batch_description',
            field=models.CharField(blank=True, default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analysisbatch',
            name='analysis_batch_notes',
            field=models.CharField(blank=True, default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analysisbatchtemplate',
            name='elution_volume',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analysisbatchtemplate',
            name='extraction_volume',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extractionbatch',
            name='elution_volume',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extractionbatch',
            name='extraction_date',
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='extractionbatch',
            name='extraction_volume',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extractionbatch',
            name='pcr_date',
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='extractionbatch',
            name='qpcr_reaction_volume',
            field=models.FloatField(default=20),
        ),
        migrations.AlterField(
            model_name='extractionbatch',
            name='qpcr_template_volume',
            field=models.FloatField(default=6),
        ),
        migrations.AlterField(
            model_name='extractionbatch',
            name='re_extraction_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extractionbatch',
            name='sample_dilution_factor',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filtertype',
            name='matrix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='lideservices.Matrix'),
        ),
        migrations.AlterField(
            model_name='finalconcentratedsamplevolume',
            name='final_concentrated_sample_volume',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inhibition',
            name='inhibition_date',
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='pcrreplicate',
            name='concentration_unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pcrreplicates', to='lideservices.Unit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pcrreplicate',
            name='gc_reaction',
            field=models.DecimalField(blank=True, decimal_places=100, max_digits=120, null=True),
        ),
        migrations.AlterField(
            model_name='pcrreplicate',
            name='replicate_concentration',
            field=models.DecimalField(blank=True, decimal_places=100, max_digits=120, null=True),
        ),
        migrations.AlterField(
            model_name='pcrreplicatebatch',
            name='re_pcr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pcrreplicatebatches', to='lideservices.PCRReplicateBatch'),
        ),
        migrations.AlterField(
            model_name='pcrreplicatebatch',
            name='replicate_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='result',
            name='sample_mean_concentration',
            field=models.DecimalField(blank=True, decimal_places=100, max_digits=120, null=True),
        ),
        migrations.AlterField(
            model_name='reversetranscription',
            name='re_rt_notes',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reversetranscription',
            name='reaction_volume',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reversetranscription',
            name='template_volume',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sample',
            name='collection_start_date',
            field=models.DateField(default='2018-03-19'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sample',
            name='technician_initials',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='total_volume_or_mass_sampled',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='target',
            name='code',
            field=models.CharField(default='', max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='target',
            name='notes',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='extractionbatch',
            name='ext_pos_bad_result_flag',
        ),
        migrations.AlterUniqueTogether(
            name='extractionbatch',
            unique_together=set([('analysis_batch', 'extraction_number', 're_extraction')]),
        ),
        migrations.AlterUniqueTogether(
            name='freezerlocation',
            unique_together=set([('freezer', 'rack', 'box', 'row', 'spot')]),
        ),
        migrations.AlterUniqueTogether(
            name='inhibition',
            unique_together=set([('sample', 'extraction_batch', 'nucleic_acid_type')]),
        ),
        migrations.RemoveField(
            model_name='pcrreplicatebatch',
            name='ext_neg_bad_result_flag',
        ),
        migrations.RemoveField(
            model_name='pcrreplicatebatch',
            name='pcr_neg_bad_result_flag',
        ),
        migrations.RemoveField(
            model_name='pcrreplicatebatch',
            name='pcr_pos_bad_result_flag',
        ),
        migrations.RemoveField(
            model_name='pcrreplicatebatch',
            name='rt_neg_bad_result_flag',
        ),
        migrations.AlterUniqueTogether(
            name='pcrreplicatebatch',
            unique_together=set([('extraction_batch', 'target', 'replicate_number', 're_pcr')]),
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together=set([('sample', 'target')]),
        ),
        migrations.DeleteModel(
            name='MatrixType',
        ),
        migrations.AddField(
            model_name='sampleextraction',
            name='extraction_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sampleextractions', to='lideservices.ExtractionBatch'),
        ),
        migrations.AddField(
            model_name='sampleextraction',
            name='inhibition_dna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sampleextractions_dna', to='lideservices.Inhibition'),
        ),
        migrations.AddField(
            model_name='sampleextraction',
            name='inhibition_rna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sampleextractions_rna', to='lideservices.Inhibition'),
        ),
        migrations.AddField(
            model_name='sampleextraction',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sampleextraction_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sampleextraction',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sampleextractions', to='lideservices.Sample'),
        ),
        migrations.AddField(
            model_name='pcrreplicate',
            name='sample_extraction',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='pcrreplicates', to='lideservices.SampleExtraction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sample',
            name='matrix',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='lideservices.Matrix'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='pcrreplicate',
            name='extraction',
        ),
        migrations.RemoveField(
            model_name='pcrreplicate',
            name='target',
        ),
        migrations.AlterUniqueTogether(
            name='pcrreplicate',
            unique_together=set([('sample_extraction', 'pcrreplicate_batch')]),
        ),
        migrations.AlterUniqueTogether(
            name='sampleextraction',
            unique_together=set([('sample', 'extraction_batch')]),
        ),
        migrations.DeleteModel(
            name='Extraction',
        ),
    ]
