# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-15 14:24
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations
import lideservices.models


class Migration(migrations.Migration):

    dependencies = [
        ('lideservices', '0010_auto_20180510_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisbatch',
            name='analysis_batch_description',
        ),
        migrations.RemoveField(
            model_name='analysisbatch',
            name='analysis_batch_notes',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='sampler_name',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='study_site_name',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='technician_initials',
        ),
        migrations.AlterField(
            model_name='aliquot',
            name='aliquot_number',
            field=lideservices.models.NonnegativeIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='analysisbatchtemplate',
            name='description',
            field=lideservices.models.BlankableTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='analysisbatchtemplate',
            name='elution_volume',
            field=lideservices.models.NonzeroDecimalField2010(decimal_places=10, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-10'))]),
        ),
        migrations.AlterField(
            model_name='analysisbatchtemplate',
            name='extraction_volume',
            field=lideservices.models.NonnegativeDecimalField2010(decimal_places=10, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='extractionbatch',
            name='elution_volume',
            field=lideservices.models.NonzeroDecimalField2010(decimal_places=10, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-10'))]),
        ),
        migrations.AlterField(
            model_name='extractionbatch',
            name='ext_pos_cq_value',
            field=lideservices.models.NullableNonnegativeDecimalField2010(blank=True, decimal_places=10, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='extractionbatch',
            name='ext_pos_gc_reaction',
            field=lideservices.models.NullableNonnegativeDecimalField120100(blank=True, decimal_places=100, max_digits=120, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='extractionbatch',
            name='extraction_number',
            field=lideservices.models.NonnegativeIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='extractionbatch',
            name='extraction_volume',
            field=lideservices.models.NonnegativeDecimalField2010(decimal_places=10, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='extractionbatch',
            name='re_extraction_notes',
            field=lideservices.models.BlankableTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='extractionbatch',
            name='sample_dilution_factor',
            field=lideservices.models.NonnegativeIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='finalconcentratedsamplevolume',
            name='notes',
            field=lideservices.models.BlankableTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='finalsamplemeanconcentration',
            name='final_sample_mean_concentration',
            field=lideservices.models.NullableNonnegativeDecimalField120100(blank=True, decimal_places=100, max_digits=120, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='freezer',
            name='boxes',
            field=lideservices.models.NonnegativeIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='freezer',
            name='racks',
            field=lideservices.models.NonnegativeIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='freezer',
            name='rows',
            field=lideservices.models.NonnegativeIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='freezer',
            name='spots',
            field=lideservices.models.NonnegativeIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='freezerlocation',
            name='box',
            field=lideservices.models.NonnegativeIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='freezerlocation',
            name='rack',
            field=lideservices.models.NonnegativeIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='freezerlocation',
            name='row',
            field=lideservices.models.NonnegativeIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='freezerlocation',
            name='spot',
            field=lideservices.models.NonnegativeIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='otheranalysis',
            name='data',
            field=lideservices.models.BlankableTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='otheranalysis',
            name='description',
            field=lideservices.models.BlankableTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pcrreplicate',
            name='cq_value',
            field=lideservices.models.NullableNonnegativeDecimalField2010(blank=True, decimal_places=10, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pcrreplicate',
            name='gc_reaction',
            field=lideservices.models.NullableNonnegativeDecimalField120100(blank=True, decimal_places=100, max_digits=120, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pcrreplicatebatch',
            name='ext_neg_cq_value',
            field=lideservices.models.NullableNonnegativeDecimalField2010(blank=True, decimal_places=10, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pcrreplicatebatch',
            name='ext_neg_gc_reaction',
            field=lideservices.models.NullableNonnegativeDecimalField120100(blank=True, decimal_places=100, max_digits=120, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pcrreplicatebatch',
            name='notes',
            field=lideservices.models.BlankableTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pcrreplicatebatch',
            name='pcr_neg_cq_value',
            field=lideservices.models.NullableNonnegativeDecimalField2010(blank=True, decimal_places=10, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pcrreplicatebatch',
            name='pcr_neg_gc_reaction',
            field=lideservices.models.NullableNonnegativeDecimalField120100(blank=True, decimal_places=100, max_digits=120, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pcrreplicatebatch',
            name='pcr_pos_cq_value',
            field=lideservices.models.NullableNonnegativeDecimalField2010(blank=True, decimal_places=10, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pcrreplicatebatch',
            name='pcr_pos_gc_reaction',
            field=lideservices.models.NullableNonnegativeDecimalField120100(blank=True, decimal_places=100, max_digits=120, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pcrreplicatebatch',
            name='replicate_number',
            field=lideservices.models.NonnegativeIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pcrreplicatebatch',
            name='rt_neg_cq_value',
            field=lideservices.models.NullableNonnegativeDecimalField2010(blank=True, decimal_places=10, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pcrreplicatebatch',
            name='rt_neg_gc_reaction',
            field=lideservices.models.NullableNonnegativeDecimalField120100(blank=True, decimal_places=100, max_digits=120, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='reversetranscription',
            name='re_rt_notes',
            field=lideservices.models.BlankableTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reversetranscription',
            name='rt_pos_cq_value',
            field=lideservices.models.NullableNonnegativeDecimalField2010(blank=True, decimal_places=10, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='reversetranscription',
            name='rt_pos_gc_reaction',
            field=lideservices.models.NullableNonnegativeDecimalField120100(blank=True, decimal_places=100, max_digits=120, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sample',
            name='arrival_notes',
            field=lideservices.models.BlankableTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='dissolution_volume',
            field=lideservices.models.NullableNonzeroDecimalField2010(blank=True, decimal_places=10, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1E-10'))]),
        ),
        migrations.AlterField(
            model_name='sample',
            name='elution_notes',
            field=lideservices.models.BlankableTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='meter_reading_final',
            field=lideservices.models.NullableNonnegativeDecimalField2010(blank=True, decimal_places=10, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sample',
            name='meter_reading_initial',
            field=lideservices.models.NullableNonnegativeDecimalField2010(blank=True, decimal_places=10, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sample',
            name='post_dilution_volume',
            field=lideservices.models.NullableNonzeroDecimalField2010(blank=True, decimal_places=10, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1E-10'))]),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_description',
            field=lideservices.models.BlankableTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_notes',
            field=lideservices.models.BlankableTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_volume_initial',
            field=lideservices.models.NullableNonnegativeDecimalField2010(blank=True, decimal_places=10, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sample',
            name='total_volume_or_mass_sampled',
            field=lideservices.models.NonnegativeDecimalField2010(decimal_places=10, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sample',
            name='total_volume_sampled_initial',
            field=lideservices.models.NullableNonnegativeDecimalField2010(blank=True, decimal_places=10, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='samplegroup',
            name='description',
            field=lideservices.models.BlankableTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='standardcurve',
            name='efficiency',
            field=lideservices.models.NullableNonnegativeDecimalField2010(blank=True, decimal_places=10, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='standardcurve',
            name='pos_ctrl_cq',
            field=lideservices.models.NullableNonnegativeDecimalField2010(blank=True, decimal_places=10, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='standardcurve',
            name='pos_ctrl_cq_range',
            field=lideservices.models.NullableNonnegativeDecimalField2010(blank=True, decimal_places=10, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='standardcurve',
            name='r_value',
            field=lideservices.models.NullableNonnegativeDecimalField2010(blank=True, decimal_places=10, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='standardcurve',
            name='slope',
            field=lideservices.models.NullableNonnegativeDecimalField2010(blank=True, decimal_places=10, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='study',
            name='description',
            field=lideservices.models.BlankableTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='notes',
            field=lideservices.models.BlankableTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='description',
            field=lideservices.models.BlankableTextField(blank=True),
        ),
    ]
