# Generated by Django 2.2 on 2019-10-11 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lideservices', '0012_auto_20191011_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalreportfile',
            old_name='report_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='reportfile',
            old_name='report_status',
            new_name='status',
        ),
    ]
